{% set name = "deepinv" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepinv-{{ version }}.tar.gz
  sha256: cb38aaae3674869b26c92cebf081a7130e87660f2a4ca9a7fed45465e282a27d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - hdf5storage
    - tqdm
    - pytorch
    - torchvision
    - torchmetrics
    - einops
    - wandb
    - scipy

test:
  imports:
    - deepinv
  commands:
    - pip check
    - pytest deepinv/tests -vs
  source_files:
    - deepinv/tests/*
    - deepinv/tests/assets/generators/*
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - datasets

about:
  summary: Pytorch library for solving inverse problems with deep learning
  dev_url: https://github.com/deepinv/deepinv
  home: https://github.com/deepinv/deepinv
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gschramm
    - tachella
    - matthieutrs
